swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "User API"
tags:
- name: "users"
  description: ""
  externalDocs:
    description: "User data source"
    url: "https://userdataapi.com/"
schemes:
- "https"
- "http"
paths:
  /users/live/city:
    get:
      tags:
      - "users"
      description: "Returns users who are listed as living in a city"
      operationId: "findUsersByLivingPlace"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        "404":
          description: "User not found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User_Error"
  /users/current/vicinity:
    get:
      tags:
      - "users"
      description: "Returns users whose current coordinates are within 50 miles of a city"
      operationId: "findCurrentUsersByVicinity"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"
        "404":
          description: "User not found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User_Error"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      first_name:
        type: "string"
      last_name:
        type: "string"
      email:
        type: "string"
      ip_address:
        type: "string"
      latitude:
        type: "string"
      longitude:
        type: "string"
    xml:
      name: "User"
  User_Error:
    type: "object"
    properties:
      status:
        type: "string"
        description: "HTTP error"
      message:
        type: "string"
        description: "user not found"
    xml:
      name: "User_Error"